name: Upload release artifacts
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_tag:
        description: "The release tag to target"

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  release-artifacts:
    runs-on: ubuntu-latest
    name: "Build and publish metadelta-cli docker image"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'release' && '' || github.event.inputs.release_tag }}

      - uses: cachix/install-nix-action@v25
        name: "Installing Nix"
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and publish docker image"
        env:
          RELEASE_TAG: ${{ github.event_name == 'release' && github.event.release.tag_name || github.event.inputs.release_tag }}
        run: |
          cd backend/
          nix build .#metadelta-docker-image
          export TARBALL_TAG="$(nix eval --raw .#metadelta-docker-image.imageName):$(nix eval --raw .#metadelta-docker-image.imageTag)"
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          export VERSION="$(echo $RELEASE_TAG | sed 's/^metadelta-//')"
          docker load -i ./result
          docker tag "$TARBALL_TAG" ghcr.io/invariantclub/metadelta:$VERSION
          docker tag "$TARBALL_TAG" ghcr.io/invariantclub/metadelta:latest
          docker push ghcr.io/invariantclub/metadelta:$VERSION
          docker push ghcr.io/invariantclub/metadelta:latest
